# Generated by Django 5.1.3 on 2024-12-19 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="first_user_id",
            new_name="first_user",
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="second_user_id",
            new_name="second_user",
        ),
    ]
