# Generated by Django 5.1.3 on 2024-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_first_user_id_chat_first_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="chat_id",
            new_name="chat",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="receiver_id",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="sender_id",
            new_name="sender",
        ),
    ]
