# Generated by Django 5.1.3 on 2024-12-19 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_assignedtask_unique_assigned_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="latest_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_message",
                to="tasks.message",
            ),
        ),
    ]
