# Generated by Django 5.1.3 on 2024-12-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_chat_latest_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="latest_message",
            field=models.TextField(null=True),
        ),
    ]
