# Generated by Django 5.1.3 on 2024-12-20 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_chat_latest_message"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chat",
            name="unique_chat",
        ),
    ]
