# Generated by Django 5.1.3 on 2024-12-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_remove_chat_unique_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="chat_id",
        ),
        migrations.AddField(
            model_name="chat",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="tasks.task",
            ),
        ),
    ]
