# Generated by Django 5.1.3 on 2024-12-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_remove_task_chat_id_chat_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="messages"),
        ),
    ]
